[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "amherst"
description = "Add your description here"
version = "0.3.16"
authors = [
    { name = "Paw", email = "amherst+pawrequest@users.noreply.github.com" }
]
readme = "README.md"
requires-python = ">= 3.13"
dependencies = [
    # siblings:
    'pycommence', # commence python api
#    'pycommence @ git+https://github.com/pawrequest/pycommence', # commence python api
    "shipaw",

    'flaskwebgui @ git+https://github.com/pawrequest/flaskwebgui@v1.2.2', # desktop-ify fastapi app
    'pawdf @ git+https://github.com/pawrequest/pawdf', # pdf resize and print
    'suppawt @ git+https://github.com/pawrequest/suppawt', # emailer
    'pawlogger @ git+https://github.com/pawrequest/pawlogger', # logger config
    'python-multipart',
    'matplotlib', # stockcheck charts
    'pydantic-settings',
    'pydantic[email]',
    'fastapi', # frontend
    'docxtpl', # doc templating
    'jinja2', # web templating
    'pandas', # excel docs
    'loguru', # logging
    'pyperclip', # clipboard management
]

[project.scripts]
shipper = "amherst.cli:shipper_cli"
print-file = "amherst.cli:file_printer_cli"
payment-status = "amherst.cli:payment_status_cli"
email-file = "amherst.cli:send_invoice_email_cli"
invoice-number = "amherst.cli:next_invoice_cli"

#[project.optional-dependencies]
#dev = [
#    "pytest",
#    "pytest_asyncio",
#    'beautifulsoup4',
#    'coverage',
#]

#docs = [
#    "sphinx",
#    "sphinx-autodoc-typehints",
#    "sphinx-autodoc2",
#    "sphinx-rtd-theme",
#    "sphinx-readme",
#    "myst-parser",
#    "sphinx_rtd_dark_mode",
#]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
line-length = 120
extend-select = ["Q", "RUF100", "UP"]
flake8-quotes = { inline-quotes = "single", multiline-quotes = "double" }
format.quote-style = "single"

[tool.uv.sources]
#shipaw = { path = "../shipaw", editable = true }
#pycommence = { path = "../pycommence", editable = true }
shipaw = { git = "git+https://github.com/pawrequest/shipaw/" }
pycommence = { git = "git+https://github.com/pawrequest/pycommence/" }

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]

