[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"


[project]
name = "amherst"
version = "0.4.9"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Paw", email = "amherst+pawrequest@users.noreply.github.com" }
]
requires-python = ">= 3.13"

dependencies = [
    "shipaw>=0.3.19",
    "pawlogger>=0.1.0",
    "pycommence>=0.2.2",
    #
    "matplotlib>=3.10.6",
    "python-multipart>=0.0.20",
    "pydantic-settings>=2.11.0",
    "pydantic[email]>=2.11.9",
    "fastapi>=0.117.1",
    "docxtpl>=0.20.1",
    "jinja2>=3.1.6",
    "pandas>=2.3.3",
    "loguru>=0.7.3",
    "pyperclip>=1.11.0",
    "xlrd>=2.0.2",
    "flaskwebgui>=1.1.6",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=1.2.0",
    "autodoc-pydantic>=2.2.0",
    "myst-parser>=4.0.1",
    "sphinx>=8.2.3",
    "sphinx-autodoc-typehints>=3.2.0",
    "sphinx-readme>=1.2.1",
    "sphinx-rtd-dark-mode>=1.3.0",
    "sphinx-rtd-theme>=3.0.2",
]


[project.scripts]
shipper = "amherst.cli:shipper_cli"
print-file = "amherst.cli:file_printer_cli"
payment-status = "amherst.cli:payment_status_cli"
email-file = "amherst.cli:send_invoice_email_cli"
invoice-number = "amherst.cli:next_invoice_cli"
convert_tracking = "amherst.cli:convert_tracking_link"

[tool.ruff]
line-length = 120
extend-select = ["Q", "RUF100", "UP"]
flake8-quotes = { inline-quotes = "single", multiline-quotes = "double" }
format.quote-style = "single"


[tool.uv.build-backend]
source-include = ["src/amherst/ui/**"]
