[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "amherst"
description = "Add your description here"
version = "0.3.11"
authors = [
    { name = "Paw", email = "amherst+pawrequest@users.noreply.github.com" }
]
readme = "README.md"
requires-python = ">= 3.13"
dependencies = [
#    'pawdantic @ git+https://github.com/pawrequest/pawdantic', # used in shipaw
    'flaskwebgui @ git+https://github.com/pawrequest/flaskwebgui@v1.2.0',
    'pawdf @ git+https://github.com/pawrequest/pawdf',
    'suppawt @ git+https://github.com/pawrequest/suppawt', # emailer
    'pawlogger @ git+https://github.com/pawrequest/pawlogger', # logger config
    'shipaw @ git+https://github.com/pawrequest/shipaw',
    'pycommence @ git+https://github.com/pawrequest/pycommence',
#    'phonenumbers',
    'matplotlib',
#    'sqlmodel',
    'pydantic-settings',
    'pydantic[email]',
#    'pydantic-extra-types',
    'fastapi',
#    'pypdf',
    'docxtpl',
    'sqlmodel',
#    'uvicorn[standard]',
#    'python-dotenv',
#    'httpx',
#    "pywin32",
    'jinja2',
    'pandas',
    'loguru',
#    'xlrd',
    'pyperclip',
]

[project.scripts]
payment-status = "amherst.actions.payment_status:payment_status_cli"
shipper = "amherst.cli:main_cli"
invoice-number = "amherst.actions.invoice_number:main"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest_asyncio",
    'beautifulsoup4',
    'coverage',
]

docs = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-autodoc2",
    "sphinx-rtd-theme",
    "sphinx-readme",
    "myst-parser",
    "sphinx_rtd_dark_mode",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
line-length = 120
extend-select = ["Q", "RUF100", "UP"]
flake8-quotes = { inline-quotes = "single", multiline-quotes = "double" }
format.quote-style = "single"

