[project]
name = "amherst"
description = "Add your description here"
version = "0.4.1"
authors = [
    { name = "Paw", email = "amherst+pawrequest@users.noreply.github.com" }
]
readme = "README.md"
requires-python = ">= 3.13"

dependencies = [
    # siblings:
    'pycommence', # commence python api
    "shipaw >= 0.3.0", # shipping api
    'flaskwebgui @ git+https://github.com/pawrequest/flaskwebgui@v1.2.2', # desktop-ify fastapi app
    'pawdf @ git+https://github.com/pawrequest/pawdf', # pdf resize and print
    'suppawt @ git+https://github.com/pawrequest/suppawt', # emailer
    'pawlogger @ git+https://github.com/pawrequest/pawlogger', # logger config
    'python-multipart',
    'matplotlib', # stockcheck charts
    'pydantic-settings',
    'pydantic[email]',
    'fastapi', # frontend
    'docxtpl', # doc templating
    'jinja2', # web templating
    'pandas', # excel docs
    'loguru', # logging
    'pyperclip', # clipboard management
    'xlrd',
    "pytest-asyncio>=1.2.0",
    "hatchling>=1.27.0",
]


[project.optional-dependencies]
dev = [
    'pytest',
    'autodoc_pydantic',
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme",
    "myst-parser",
    "sphinx-readme",
    "sphinx_rtd_dark_mode",
]


[project.scripts]
shipper = "amherst.cli:shipper_cli"
print-file = "amherst.cli:file_printer_cli"
payment-status = "amherst.cli:payment_status_cli"
email-file = "amherst.cli:send_invoice_email_cli"
invoice-number = "amherst.cli:next_invoice_cli"
convert_tracking = "amherst.cli:convert_tracking_link"

[tool.ruff]
line-length = 120
extend-select = ["Q", "RUF100", "UP"]
flake8-quotes = { inline-quotes = "single", multiline-quotes = "double" }
format.quote-style = "single"

[tool.uv.sources]
shipaw = { git = "https://github.com/pawrequest/shipaw", branch = "v3" }
pycommence = { git = "git+https://github.com/pawrequest/pycommence/", tag = "v0.2.2" }

[project.optional-dependencies]
dev = [
    'pytest',
    'autodoc_pydantic',
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme",
    "myst-parser",
    "sphinx-readme",
    "sphinx_rtd_dark_mode",
]

[tool.uv.sources]
shipaw = { git = "https://github.com/pawrequest/shipaw", branch = "v3" }
pycommence = { git = "git+https://github.com/pawrequest/pycommence/", tag = "v0.2.2" }

#[build-system]
#requires = ["uv_build>=0.8.22,<0.9.0"]

[tool.uv.build-backend]
source-include = ["src/amherst/ui/**"]
